spring:
  datasource:
    url: jdbc:mysql://puddy-db.cpg0bs4xqbye.ap-northeast-2.rds.amazonaws.com:3306/gram?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: create